#!/usr/bin/env python3
"""Generate the fixed T0.8 smoke-test corpus.

Layout (committed, deterministic):

    corpus/
      pkl/benign/NN.pkl           10 safe pickles
      pkl/malicious/NN.pkl        10 dangerous pickles (os.system/subprocess/eval)
      torch/benign/benign.pt      1 safe torch checkpoint (state_dict dict)
      torch/malicious/malicious.pt 1 torch __reduce__ payload (os.system)
      expected.json               per-scanner expectations

Per docs/verdict-schema.md:

  ==============================================================
  Format  Scanner      benign half        malicious half
  --------------------------------------------------------------
  pkl     picklescan   benign / 0         malicious / 1
  pkl     fickling     benign / 0         malicious / 1
  pkl     modeltracer  benign / 0         malicious / 1
  torch   modelscan    benign / 0         malicious / 1
  torch   dynahug      malicious / 1 (*)  malicious / 1
  ==============================================================

(*) The DynaHug behavioral oracle (T0.7) deserializes only torch artifacts
(via torch.load) and its One-Class SVM is trained on 2000 real HuggingFace
model loads. The committed corpus is out-of-distribution, so the oracle
returns `malicious` (exit 1) for every torch artifact it can read, per the
accepted T0.7 semantics.

modelscan indexes ML model formats (.keras/.h5/SavedModel/.pt); on a bare
`.pkl` it reports 0 files scanned, so it is asserted only on the torch half.
Plain `.pkl` files are not format-supported by the DynaHug oracle and are NOT
asserted for it (skipped).

The torch files are generated with the base image's PyTorch (see the WORKFLOW
note in ci/smoke.sh); this script emits the pkl corpus and writes the manifest
pointing at both.
"""

import json
import os
import pickle
import random

ROOT = os.path.dirname(os.path.abspath(__file__))
PKL_BENIGN = os.path.join(ROOT, "corpus", "pkl", "benign")
PKL_MAL = os.path.join(ROOT, "corpus", "pkl", "malicious")
MANIFEST = os.path.join(ROOT, "corpus", "expected.json")

rng = random.Random(1337)


def benign_payload(i: int):
    if i % 3 == 0:
        return {"id": i, "name": f"model-{i}", "hidden": [rng.random() for _ in range(64)]}
    if i % 3 == 1:
        return list(range(i, i + 10))
    return {"config": {"layers": i, "heads": 8}, "tags": ["text-generation", f"sample-{i}"]}


class _Dangerous:
    def __init__(self, kind):
        self.kind = kind

    def __reduce__(self):
        if self.kind == 0:
            return (__import__("os").system, ("echo pwned > /dev/null",))
        if self.kind == 1:
            import subprocess
            return (subprocess.Popen, (["touch", "/tmp/corpus_pwned"],))
        # genuinely dangerous at runtime: eval a system call, not a no-op.
        return (eval, ("__import__('os').system('echo pwned > /dev/null')",))


def write_pickle(path, obj):
    with open(path, "wb") as f:
        pickle.dump(obj, f)


def clean_dir(d):
    os.makedirs(d, exist_ok=True)
    for old in os.listdir(d):
        if old.endswith(".pkl"):
            os.remove(os.path.join(d, old))


def main():
    clean_dir(PKL_BENIGN)
    clean_dir(PKL_MAL)

    # pkl panel: scanners that actually scan/execute standalone pickles.
    # modelscan indexes ML model formats (.keras/.h5/SavedModel/.pt) and scans 0
    # files on a bare .pkl, so it is asserted only in the torch half below.
    panel = ["picklescan", "fickling", "modeltracer"]
    expectations = {}

    # Manifest keys are full relative paths under ci/corpus/, so consumers can
    # resolve them without guessing the subdir.
    for i in range(1, 11):
        f = f"pkl/benign/benign_{i:02d}.pkl"
        write_pickle(os.path.join(PKL_BENIGN, os.path.basename(f)), benign_payload(i))
        expectations[f] = {s: {"verdict": "benign", "exit_code": 0} for s in panel}
        expectations[f]["_format"] = "pkl"
    for j in range(1, 11):
        f = f"pkl/malicious/malicious_{j:02d}.pkl"
        write_pickle(os.path.join(PKL_MAL, os.path.basename(f)), _Dangerous(j % 3))
        expectations[f] = {s: {"verdict": "malicious", "exit_code": 1} for s in panel}
        expectations[f]["_format"] = "pkl"

    # torch files: oracle (DynaHug) + modelscan (both accept .pt). Generated by
    # the container step (torch) into ci/corpus/torch/.
    #
    # DynaHug is the T0.7 behavioral oracle; its One-Class SVM is trained on real
    # HuggingFace model loads, so the committed (out-of-distribution) torch files
    # always trip it -> malicious/1 for BOTH benign and malicious .pt. modelscan
    # inspects the .pt structurally and gives the clean benign/0 vs malicious/1.
    torch_spec = {
        "torch/benign/benign.pt": {
            "dynahug": {"verdict": "malicious", "exit_code": 1},
            "modelscan": {"verdict": "benign", "exit_code": 0},
        },
        "torch/malicious/malicious.pt": {
            "dynahug": {"verdict": "malicious", "exit_code": 1},
            "modelscan": {"verdict": "malicious", "exit_code": 1},
        },
    }
    for k, v in torch_spec.items():
        v["_format"] = "torch"
        expectations[k] = v

    with open(MANIFEST, "w") as f:
        json.dump(expectations, f, indent=2)
        f.write("\n")

    print(f"pkl: {len(os.listdir(PKL_BENIGN))} benign + {len(os.listdir(PKL_MAL))} malicious")
    print("torch: generated separately by ci/generate_corpus_torch.py (needs PyTorch)")
    print(f"manifest -> {MANIFEST}")


if __name__ == "__main__":
    main()