#!/bin/sh
# T0.8 smoke test: build the scanner/oracle panel, generate the torch corpus
# (needs PyTorch, only present in the base image), then run ci/smoke.py against
# every committed artifact and assert each (verdict, exit_code) matches
# ci/corpus/expected.json.
#
# Usage:
#   ./ci/smoke.sh            # full run (build + corpus gen + assertions)
#   ./ci/smoke.sh --no-build # reuse already-built local images
#
# Exit 0 on full pass, non-zero on any build/corpus/assertion failure.

set -e
cd "$(dirname "$0")/.."   # repo root

BUILD=1
case "$1" in
  --no-build) BUILD=0 ;;
  "") : ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
esac

BACKEND="${SMOKE_BACKEND:-podman}"

BUILD_DIRS="base picklescan modelscan fickling modeltracer dynahug"

if [ "$BUILD" = "1" ]; then
  # Build order matters: each scanner FROM the base image.
  for d in $BUILD_DIRS; do
    if [ ! -x "containers/$d/build.sh" ]; then
      echo "missing build script containers/$d/build.sh" >&2
      exit 2
    fi
    echo "==> building regenbench/$d"
    "containers/$d/build.sh"
  done
fi

# The torch (.pt) artifacts are generated by the base image (it carries
# PyTorch), which the host may not. The pkl corpus is committed in the repo and
# not regenerated here. Running in-container keeps artifact bytes deterministic.
echo "==> generating torch corpus"
mkdir -p ci/corpus/torch/benign ci/corpus/torch/malicious
"$BACKEND" run --rm \
  -v "$PWD:/repo:z" \
  --entrypoint python3.13 \
  regenbench/base:latest \
  /repo/ci/generate_corpus_torch.py /repo/ci/corpus/torch

echo "==> running assertions"
python3 ci/smoke.py --backend "$BACKEND" --tag :latest